site:
  baseline: Uriel's new blog
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Asia/Singapore
  description: 'Starter blog, with Netlify CMS.'
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: Cecil
theme: hyde
